FROM bpi/webapp-base:stack as builder

ARG STACK_BUILD_TOOL
ARG STACK_BUILD_OUTPUT_DIR

WORKDIR /app
COPY . .
RUN rm -rf node_modules build dist .next*
RUN /scripts/build-app.sh /app /data

FROM bpi/webapp-base:stack
COPY --from=builder /data /data
