FROM bpi/webapp-base:local as builder

ARG BPI_BUILD_TOOL
ARG BPI_BUILD_OUTPUT_DIR

WORKDIR /app
COPY . .
RUN rm -rf node_modules build dist .next*
RUN /scripts/build-app.sh /app /data

FROM bpi/webapp-base:local
COPY --from=builder /data /data
