name: Clean Releases
on:  
  push:
    branches:
      - clean-test
  schedule:
    - cron: '00 1 * * *'  # At 01:00 on Mondays.

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: bozemanpass/stack

jobs:
  clean:
    name: Clean Old Releases
    runs-on: ubuntu-24.04
    steps:
      - name: "Remove all but the last 15 releases"
        run: |
          for release in $(gh release list --json tagName --limit 200 | jq -r '.[] | .tagName' | tail -n +15; do
            gh release delete --cleanup-tag -y "$release"
          done
