name: CI Test

on:
  push:
    branches:
      - 'test-ci'

jobs:
  test:
    name: "Test CI jobs"
    runs-on: ubuntu-24.04
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: "Print Python version"
        run: python3 --version
      - name: "Run kind"
        run: kind version
      - name: "See where kind is installed"
        run: which kind
      - name: "Check timestamp on kind binary"
        run: ls -l /usr/local/bin

